### ISSUE TITLE
顧客受注番号を表示に含めて売上検索するとエラー

### ISSUE THREAD

**Issue by bas-miyata** [solcom-net/KIDS#7]
### 再現手順
1. 売上検索画面（sc/search/index.php）に遷移する
1. 顧客受注番号の「表示」チェックボックスをONにする
1. 入力者に「169」を設定して「検索」ボタンを押す

### 発生する事象
以下のエラーが発生。

pg_query(): Query failed: ERROR: column tsd.lngreceiveno does not exist LINE 38: left join m_Receive r on r.lngreceiveno = tsd.lngreceiveno ^ HINT: Perhaps you meant to reference the column "s.lngreceiveno".
LINE 258 FILE E:\Source\Repos\solcom-net\KIDS\01_kidsweb\home\kids2\lib\clsdb.php
strSessionID=7b6b21486d5b6c9fc5a6e003fc814e39mb_send_mail(): Failed to connect to mailserver at "localhost" port 25, verify your "SMTP" and "smtp_port" setting in php.ini or use ini_set()

### 期待される動作
検索結果が表示される

### 直接の原因
sc/cmn/lib_scs.php
```
if ( $flgReceive )
{
 $aryFromQuery[] = "	left join t_salesdetail tsd";
 $aryFromQuery[] = "	on tsd.lngsalesno = s.lngsalesno";
 $aryFromQuery[] = "		left join m_Receive r on r.lngreceiveno = tsd.lngreceiveno";
}
```

「tsd.lngreceiveno」とあるが、t_salesdetailテーブルにlngreceivenoカラムは存在しないためエラーとなっている。「s.lngreceiveno」の間違いではないか？（sはm_Salesテーブル）

**Comment by kn-akajima** [comment]
lngreceivenoはm_salesからt_salesdetailに移動させたのですが、渡したダンプにはそれが反映されていないと思われます。
あす、移動したバージョンのものを渡します。

**Comment by bas-miyata** [comment]
テーブル定義修正後、エラー無く動作することを確認しました。
ご対応ありがとうございます。
